# Generated by Django 2.2.4 on 2019-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='repos',
        ),
        migrations.AddField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
